config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

# about page
  get 'pages/about'

# contact page
  get 'pages/contact'

# home page
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "200x>", thumb: "200x200>" }, default_url: "default.jpg"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#validates name upon sign up
         # validates :name, presence: true

         has_many :products, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def check_user
          if current_user !=@listing.user
          redirect_to root_url, alert:"Sorry, this listing belongs to someone else"
    end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #this below is code taken from the devise website.
  #it adds strong perameters to our sign in. we are adding names to sign in accounts


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/helpers/devise_helper.rb
# the below code is for an alert banner

module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<h6>Copyright Con Allen</h6>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">

<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">Tech Store Direct</a>


<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
<!-- the below is a ruby links for the site navigaton -->
  <li><%= link_to "About", pages_about_path%></li>
  <li><%= link_to "Contact", pages_contact_path%></li>
</ul>
 <ul class="nav navbar-nav navbar-right"#8581d3>
<!-- the below if statement is to display links accordingly-->
    <% if user_signed_in? %>

   <li><%= link_to "Edit Profile",edit_user_registration_path %></li>
   <li><%= link_to "Sign Out",destroy_user_session_path, method: :delete %></li>

  <% else %>


   <li><%= link_to "Admin sign in",new_user_session_path %></li>
  <% end %>
  </ul>
<form class="navbar-form navbar-left">


</form>


</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myappcon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%= render '/layouts/navbar' %>
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
  <body>


    <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
   <div class="alert alert-success" -<%= name == :notice ? "success" : "danger" %> "alert-dismissable">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
     <%= content_tag :div, msg, :id => "flash_#{name}" %>
   </div>
  <% end %>
  <% end %>
      <div class="container">
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </div>
  <%# the code below is was found online for bootstrap alerts with using devise %>


        <%= render '/layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h3>Welcome to Tech Store Direct, Irelands leading tech discount store. Please subscribe your email
on our home page to be in with a chance to win daily free prizes.
</h3>

app/views/pages/contact.html.erb
<h2>Contact us at allenconallen46@gmail.com</h2>

app/views/products/_form.html.erb
<%= form_for(@product, html: { multipart: true }) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div>


  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/index.html.erb
<%# jumbotron below %>
<div class="jumbotron">
  <h2 class="display-3"><B>Welcome to Tech Store Direct</B></h2>
  <h4>Irelands leading online discount store for everything tech!</h4>
  <hr class="my-2">
  <div class="container">
  <h3>Please subscribe with your email below to win instant daily prizes!</h3>
  <form>
    <div class="form-group">
      <!-- Begin MailChimp Signup Form -->
      <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
      <style type="text/css">
      	#mc_embed_signup{background:#8581d3; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}

        /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
      	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
      </style>
      <div id="mc_embed_signup">
      <form action="//facebook.us15.list-manage.com/subscribe/post?u=4adcf68b355ae78e37c789178&amp;id=907fb9ea93" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
      	     <label for="mce-EMAIL"></label>
      	      <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_4adcf68b355ae78e37c789178_907fb9ea93" tabindex="-1" value=""></div>
          <div class="clear"><input type="submit" class="btn btn-success" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" onclick="validate()"></div>

          </div>
        </div>
      </form>
    </div>
      </div>
      </form>
      </div>
    </form>
    <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3">
      <div class="thumbnail">
          <%= image_tag product.image.url %><br>
            <div class="caption">
              <h3><%= product.name %><br></h3>
              <p><%= product.price %><br></p>
                  <%= link_to 'Show', product, class: "btn btn-link" %><br>
                  <% if (user_signed_in?) && (current_user == product.user) %>
       <p><%= link_to 'Edit', edit_product_path(product),class:" btn btn-link" %><p>
       <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },class:" btn btn-link" %><p>
 <% end %>
          </div>
        </div>
     <br>
 </div>
  <% end %>
 </div>



 <%#the code below hides the new listng button unless your signed in%>
    <% if user_signed_in?%>
 <%= link_to 'New Product', new_product_path, class: " btn btn-success" %>
 <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
    <%= image_tag @product.image.url %>
  </div>
</div>
  <div class="col-md-6">
    <h3><%= @product.name %></h3>
    <p> <%= @product.price %></p>
    <h5><%= @product.description %></h5>
  </div>
</div>




<%= link_to 'Edit', edit_product_path(@product),class: "btn btn-link" %> |
<%= link_to 'Back', products_path,class: "btn btn-link" %>